# tmux system copy/paste for OS X
# latest tmux don't require reattach-to-user-namespace for 2.6 or later
# https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard/issues/66

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"
